[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "aave-v3-core/=lib/aave-v3-core/",
  "erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
  "forge-std/=lib/forge-std/src/",
  "halmos-cheatcodes/=lib/openzeppelin-contracts/lib/halmos-cheatcodes/src/",
  "openzeppelin-contracts/=lib/openzeppelin-contracts/",
  "periphery/=lib/periphery/contracts/",
  "v2-periphery/=lib/v2-periphery/contracts/"
]

solc_version = "0.8.30"
